[build]
  publish = "dist/fuse/browser"
  command = "npm run build"

[[redirects]]
  from = "/api/supabase/*"
  to = "https://pw.eom.de:8443/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
